# pylint: disable=C0111
## Autogenerated config.py
##
## NOTE: config.py is intended for advanced users who are comfortable
## with manually migrating the config file on qutebrowser upgrades. If
## you prefer, you can also configure qutebrowser using the
## :set/:bind/:config-* commands without having to write a config.py
## file.
##
## Documentation:
##   qute://help/configuring.html
##   qute://help/settings.html

## This is here so configs done via the GUI are still loaded.
## Remove it to not load settings done via the GUI.
config.load_autoconfig(True)

c.auto_save.session = True
c.backend = "webengine"
c.changelog_after_upgrade = 'minor'

# Set Colorscheme
config.source("gruvbox.py")
c.completion.cmd_history_max_items = 100
c.completion.delay = 0
c.completion.height = '40%'
c.completion.open_categories = ['searchengines', 'quickmarks', 'bookmarks', 'history', 'filesystem']
c.completion.quick = True
c.completion.timestamp_format = '%Y-%m-%d %H:%M'
c.content.autoplay = False

c.content.blocking.adblock.lists = ['https://easylist.to/easylist/easylist.txt', 'https://easylist.to/easylist/easyprivacy.txt']
c.content.blocking.hosts.block_subdomains = True
c.content.blocking.hosts.lists = ['https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts']
c.content.blocking.method = 'auto'
c.content.blocking.whitelist = []
c.content.cookies.accept = 'no-3rdparty'
c.content.cookies.store = True
c.content.desktop_capture = 'ask'
c.content.dns_prefetch = True
c.content.geolocation = 'ask'
c.content.headers.accept_language = "en-US,en;q=0.9"
c.content.headers.user_agent = 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'
c.content.hyperlink_auditing = False
c.content.images = True
c.content.javascript.alert = True
c.content.javascript.enabled = True
c.content.local_content_can_access_remote_urls = True
c.content.local_content_can_access_file_urls = True
c.content.local_storage = True
c.content.pdfjs = True
c.content.prefers_reduced_motion = False
c.downloads.location.directory = "/home/jason/downloads/"
c.downloads.location.prompt = False
c.editor.command = ['kitty', '-e', 'nvim', '{file}', '-c', 'normal {line}G{column0}l']


# File/Folder Selections
c.fileselect.single_file.command = ["kitty", "-e", "ranger", "--choosedir={}"]
c.fileselect.handler = 'external'
c.fileselect.single_file.command = ["kitty", "-e", "ranger", "--choosefiles={}"]
c.fileselect.single_file.command = ["kitty", "-e", "ranger", "--choosefile={}"]

c.fonts.default_size = '12pt'
c.fonts.hints = 'bold 14px Monospace'
c.hints.uppercase = True
c.input.insert_mode.auto_load = True
c.input.insert_mode.leave_on_load = True
c.scrolling.smooth = True

## Page(s) to open at the start.
c.url.start_pages = 'http://localhost:8000'
c.url.default_page = 'http://localhost:8000'

# Bindings
config.unbind("H")
config.unbind("L")
config.unbind("J")
config.unbind("K")
config.bind("L", "tab-next")
config.bind("H", "tab-prev")
config.bind("J", "back")
config.bind("K", "forward")
config.bind("m", "hint links spawn mpv {hint-url}")
config.bind("M", "hint links spawn kitty youtube-dl {hint-url}")
config.bind("xb", "config-cycle statusbar.show always never")
config.bind("xt", "config-cycle tabs.show always never")
config.bind("xx", "config-cycle tabs.show always never ;; config-cycle statusbar.show always never")
config.bind(",x", "hint images spawn feh {hint-url}")

# Custom Search Engines
c.url.searchengines["a"] = "https://wiki.archlinux.org/?search={}"
c.url.searchengines["g"] = "http://www.google.com/search?q={}"
c.url.searchengines["y"] = "https://www.youtube.com/results?search_query={}"
c.url.searchengines["gh"] = "https://github.com/search?q={}&type=Code"
c.url.searchengines["r"] = "https://reddit.com/r/{}"

config.bind(',p', 'spawn --userscript qute-pass --mode gopass')
config.bind(',P', 'spawn --userscript qute-pass --mode gopass --password-only')
